spring:
  config:
    import: optional:nacos:${spring.application.name}.yml
  application:
    name: transaction-service
    bad_request: 400
    conflict: 409
    ok: 200

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yaml

  redis:
    host: localhost
    port: 6379

  datasource:
    url: jdbc:mysql://localhost:3307/transaction_service
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


seata:
  enabled: false



server:
  port: 8084