server:
  port: 8080

app:
  config:
    jwt:
      secret: "c2VjdXJlLXNlY3JldC1rZXktZm9yLWp3dC1zaWduaW5nLWJhbmtpbmctYXBwLW1pY3Jvc2VydmljZXM="

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: user-auth
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/accounts/**
        - id: sequence-generator
          uri: lb://sequence-generator
          predicates:
            - Path=/sequence/**
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/transactions/**
        - id: fund-transfer-service
          uri: lb://fund-transfer-service
          predicates:
            - Path=/fund-transfers/**

    sentinel:
      transport:
        dashboard: localhost:8089
      scg:
        fallback:
          mode: response
          response-status: 429
          response-body: "{\"code\":429,\"message\":\"Too many requests. Please try again later.\"}"
