server:
  port: 8080

app:
  config:
    jwt:
      secret: "c2VjdXJlLXNlY3JldC1rZXktZm9yLWp3dC1zaWduaW5nLWJhbmtpbmctYXBwLW1pY3Jvc2VydmljZXM="

spring:
  config:
    import: optional:nacos:${spring.application.name}.yml
  application:
    name: api-gateway

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yaml
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: user-auth
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/accounts/**
        - id: sequence-generator
          uri: lb://sequence-generator
          predicates:
            - Path=/sequence/**
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/transactions/**
        - id: fund-transfer-service
          uri: lb://transaction-service
          predicates:
            - Path=/fund-transfers/**
          filters:
            - RewritePath=/fund-transfers, /transactions/fund-transfers

    sentinel:
      eager: true
      transport:
        dashboard: localhost:8089
      scg:
        fallback:
          mode: response
          response-status: 429
          response-body: "{\"code\":429,\"message\":\"Too many requests. Please try again later.\"}"
