server:
  port: 8085

spring:
  devtools:
    restart:
      enabled: false
  config:
    import: optional:nacos:${spring.application.name}.yml
  application:
    name: fund-transfer-service
    bad_request: 400
    ok: 200

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yaml
    sentinel:
      eager: true
      transport:
        dashboard: localhost:8089

  datasource:
    url: jdbc:mysql://localhost:3307/fund_transfer_service
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

feign:
  sentinel:
    enabled: true

seata:
  enabled: true
  application-id: ${spring.application.name} # 告诉 TC 我是谁
  tx-service-group: my_test_tx_group # 事务分组名
  # 👇 绝杀2：你心心念念的强一致性 XA 模式！
  data-source-proxy-mode: XA
  service:
    vgroup-mapping:
      my_test_tx_group: default # 映射到 TC 集群
    grouplist:
      default: 127.0.0.1:8091 # 你的 Seata Server 地址