server:
  port: 8082

spring:
  application:
    name: user-service
    bad_request: 400
    conflict: 409
    success: 200
    not_found: 404

  datasource:
    url: jdbc:mysql://localhost:3307/user_service?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


app:
  config:
    keycloak:
      server-url: http://localhost:8180     # 【修改 2】改为 Docker 映射的 8180 端口
      realm: banking-realm                  # 【修改 3】改为我们创建的 Realm 名称
      client-id: banking-client             # 【修改 4】改为我们刚才创建的 Client ID
      client-secret: KBgH665Gr0CFEd32afg9G39pXUuDdIg5

